"""
Midasbuy API service.

encrypt_msg is generated by calling window.xMidas() via Playwright on the
live redeem page — this is the only reliable method because the Tencent
Chaos VM adds browser fingerprinting data and uses a non-standard key
schedule.

Endpoints confirmed from browser DevTools:
  Player lookup : POST /interface/getCharac
  Code info     : POST /interface/shelfProto/shelves_svr/QueryRedeemCodeInfo
"""
import asyncio
import httpx
import logging

from .schemas import PlayerInfo, PlayerLookupResponse, RedeemRequest, RedeemResponse

logger = logging.getLogger(__name__)

_BASE = "https://www.midasbuy.com"
_APPID = "1900000047"   # PUBG Mobile
_PF = "mds_pc_browser-yy-android-midasweb-midasbuy-self.midasbuy_saas"

_BASE_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    ),
    "Referer":    "https://www.midasbuy.com/",
    "Origin":     "https://www.midasbuy.com",
    "Content-Type": "application/json",
}


def _headers(cookies: str | None) -> dict:
    h = dict(_BASE_HEADERS)
    if cookies:
        h["Cookie"] = cookies
    return h


async def _encrypt(payload: dict, storage_state_path: str, country_code: str) -> dict | None:
    """Run build_encrypted_envelope in a thread pool (sync Playwright can't run in event loop)."""
    from accounts.services.playwright_crypto import build_encrypted_envelope
    return await asyncio.to_thread(build_encrypted_envelope, payload, storage_state_path, country_code)


async def get_player_info(
    player_id: str,
    country_code: str = "bd",
    storage_state_path: str | None = None,
    cookies: str | None = None,
) -> PlayerLookupResponse:
    if not storage_state_path:
        return PlayerLookupResponse(success=False, error="No session. Please log in to a Midasbuy account first.")

    raw_payload = {
        "roleId":   player_id,
        "appId":    _APPID,
        "game":     "pubgm",
        "pf":       _PF,
        "country":  country_code.upper(),
    }

    envelope = await _encrypt(raw_payload, storage_state_path, country_code)
    if not envelope:
        return PlayerLookupResponse(success=False, error="Failed to generate encrypted payload. Check Midasbuy session.")

    url = _BASE + "/interface/getCharac"
    try:
        async with httpx.AsyncClient(headers=_headers(cookies), timeout=20) as client:
            resp = await client.post(url, json=envelope)
    except Exception as exc:
        return PlayerLookupResponse(success=False, error=f"Network error: {exc}")

    if resp.status_code != 200:
        return PlayerLookupResponse(success=False, error=f"HTTP {resp.status_code}")

    try:
        data = resp.json()
    except Exception:
        return PlayerLookupResponse(success=False, error="Invalid JSON response")

    if data.get("ret") != 0:
        return PlayerLookupResponse(success=False, error=data.get("msg") or f"API error ret={data.get('ret')}")

    info = data.get("info", {})
    return PlayerLookupResponse(
        success=True,
        player=PlayerInfo(
            player_id=player_id,
            username=info.get("charac_name") or "",
            role_id=info.get("openid") or player_id,
            server_id="",
            zone_id=str(info.get("zoneid") or ""),
        ),
    )


async def query_code_info(
    player_id: str,
    pin_code: str,
    country_code: str = "bd",
    storage_state_path: str | None = None,
    cookies: str | None = None,
) -> RedeemResponse:
    if not storage_state_path:
        return RedeemResponse(success=False, message="No session.")

    raw_payload = {
        "roleId":   player_id,
        "appId":    _APPID,
        "game":     "pubgm",
        "pf":       _PF,
        "country":  country_code.upper(),
        "code":     pin_code,
        "channel":  "MIDASBUY_REDEEM",
    }

    envelope = await _encrypt(raw_payload, storage_state_path, country_code)
    if not envelope:
        return RedeemResponse(success=False, message="Failed to generate encrypted payload.")

    url = _BASE + "/interface/shelfProto/shelves_svr/QueryRedeemCodeInfo"
    try:
        async with httpx.AsyncClient(headers=_headers(cookies), timeout=20) as client:
            resp = await client.post(url, json=envelope)
    except Exception as exc:
        return RedeemResponse(success=False, message=f"Network error: {exc}")

    try:
        data = resp.json()
    except Exception:
        return RedeemResponse(success=False, message="Invalid JSON response", raw=None)

    ret = data.get("ret", -1)
    if ret != 0:
        return RedeemResponse(
            success=False,
            message=data.get("msg") or f"Code error: {data.get('err_code', 'unknown')}",
            raw=data,
        )

    products = data.get("redeem_code_info", {}).get("products", [])
    desc = ", ".join(p.get("name", "") for p in products) if products else "Unknown reward"
    return RedeemResponse(success=True, message=f"Code valid: {desc}", raw=data)


async def submit_redeem(
    player_id: str,
    pin_code: str,
    country_code: str = "bd",
    storage_state_path: str | None = None,
    cookies: str | None = None,
) -> RedeemResponse:
    check = await query_code_info(player_id, pin_code, country_code, storage_state_path, cookies)
    if not check.success:
        return check

    raw_payload = {
        "roleId":    player_id,
        "appId":     _APPID,
        "game":      "pubgm",
        "pf":        _PF,
        "country":   country_code.upper(),
        "code":      pin_code,
        "channel":   "MIDASBUY_REDEEM",
        "channelId": "MIDASBUY_REDEEM",
    }

    envelope = await _encrypt(raw_payload, storage_state_path, country_code)
    if not envelope:
        return RedeemResponse(success=False, message="Failed to generate encrypted payload.")

    url = _BASE + "/interface/shelfProto/shelves_svr/RedeemCode"
    try:
        async with httpx.AsyncClient(headers=_headers(cookies), timeout=20) as client:
            resp = await client.post(url, json=envelope)
    except Exception as exc:
        return RedeemResponse(success=False, message=f"Network error: {exc}")

    try:
        data = resp.json()
    except Exception:
        return RedeemResponse(success=False, message="Invalid JSON response")

    ret = data.get("ret", -1)
    msg = data.get("msg", "")
    return RedeemResponse(
        success=(ret == 0),
        message=msg or ("Redeemed successfully!" if ret == 0 else "Redemption failed"),
        raw=data,
    )
